# .tools/DATABASE/Loaders/LOADERengine.py
import os
import time

import logging

import cloudscraper
import json
import random
import re
import requests
import sqlite3
import unicodedata

from bs4 import BeautifulSoup
from datetime import datetime
from typing import List, Optional

LOG = logging.getLogger(__name__)

class LoaderEngine:

    """
    Generic product catalog scraping engine.

    Reads configuration (domains, CSS selectors, VAT rates)
    from CORE/__RESOURCES/websites.json and connects to the SQLite 
    databases generated by SITEMAPengine to retrieve active URLs.
    Extracts HTML/JSON-LD data and saves it to CSV.
    """
    # === INTERNAL PARAMETER(S) ===
    RESOURCES_PATH = ".tools/DATABASE/__resources/"
    SITEMAPS_PATH = ".tools/DATABASE/Sitemaps/db/"
    DATABASE_PATH = ".tools/DATABASE/Loaders/db/"

    REQUEST_DELAY = 1.0  # politeness delay between HTTP calls
    MAX_RETRIES = 3
    RETRY_DELAY = 5      # in seconds
    SAVE_COUNTER = 0
    SAVE_THRESHOLD = 10 # RAM savings

    def __init__(self, site_key: str):

        # === INTERNAL VARIABLE(S) ===
        self.WEBSITE = site_key.upper()
        self.WEBSITEcfg = self._load_config(config=os.path.join(self.RESOURCES_PATH, "websites.json"), key=self.WEBSITE)
        self.BRANDS = self._load_config(config=os.path.join(self.RESOURCES_PATH, "brands.json"))

        self.DOMAIN = self.WEBSITEcfg.get("domain", "")
        self.SELECTORS = self.WEBSITEcfg.get("selectors", {})
        self.SITEMAPindex = self.WEBSITEcfg.get("sitemap_index") or ""
        self.VAT_RATE = float(self.WEBSITEcfg.get("vat_rate", 1.21))

        self.SITEMAP_DB_PATH = os.path.join(self.SITEMAPS_PATH, f"{self.WEBSITE}_sitemaps.db")

        # === INTERNAL SERVICE(S) ===
        self._init_schema(path=self.DATABASE_PATH, name=self.WEBSITE)

        # === PARAMETERS & OPTIONS SETUP (CloudSCRAPER) ===
        self.requests = cloudscraper.create_scraper(
            browser={
                'browser': 'chrome',
                'platform': 'windows',
                'desktop': True
            }
        )

        self.REQUESTS_HEADERS = {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36',
            'Referer': f'https://www.{self.DOMAIN}/' if self.DOMAIN else '',
            'Accept-Language': 'fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7',
            'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8',
            'Connection': 'keep-alive',
            'DNT': '1' # Do Not Track
        }

    # === LOADER(S) ===
    def _load_config(self, config: str, key: Optional[str] = None) -> dict:

        """
        Loads specific configuration from a given input.
        If 'key' is None, returns the entire JSON content.

        Fetches the required metadata for the specified site, including
        base URLs, sitemap locations, and the precise HTML selectors
        (tags, classes, or IDs) needed for product data extraction.
        """
        try:
            with open(config, encoding="utf-8") as f:
                CONFIGS = json.load(f)

            # If no key
            if key is None:
                return CONFIGS

            BALISES = CONFIGS.get(key)

            if not BALISES:
                raise KeyError(f"Key value '{key}' not in {os.path.basename(config)}")

            return BALISES

        except Exception as e:
            LOG.error(f"An error occurred during READ: {e}")
            return {}
        
    def _get_active_urls_from_db(self) -> List[str]:
        if not os.path.exists(self.SITEMAP_DB_PATH):
            LOG.error(f"Sitemap database not found at {self.SITEMAP_DB_PATH}. Please run SITEMAPengine first.")
            return []

        try:
            with sqlite3.connect(self.SITEMAP_DB_PATH) as conn:
                rows = conn.execute(
                    "SELECT url FROM sitemap_urls WHERE site_key = ? AND is_active = 1",
                    (self.WEBSITE,)
                ).fetchall()
            
            urls = [r[0] for r in rows]
            LOG.info(f"Loaded {len(urls)} active URLs from SITEMAP database for {self.WEBSITE}.")
            return urls
            
        except Exception as e:
            LOG.exception(f"Error reading SITEMAP SQLite DB: {e}")
            return []
        
    # === INITIALIZER(S) ===
    def _init_schema(self, path: str, name: str) -> None:
        
        """
        Initializes the SQLite database schema for the target website.

        Connects to the site-specific database file (creating it if necessary) 
        and sets up the 'sitemap_urls' table. This table is used to track 
        discovered product URLs, their discovery timestamps, and their active 
        status, along with the necessary indices for query optimization.
        """
        with sqlite3.connect(os.path.join(path, f"{name}_database.db")) as conn:
            conn.execute("""
                CREATE TABLE IF NOT EXISTS products (
                    id                  INTEGER PRIMARY KEY AUTOINCREMENT,
                    site_key            TEXT NOT NULL,
                    url                 TEXT NOT NULL UNIQUE,
                    ean                 TEXT,
                    mpn                 TEXT,
                    brand               TEXT,
                    article             TEXT,
                    catalog_price_htva  REAL,
                    catalog_price_ttc   REAL,
                    catalog_date        TEXT,
                    live_price_htva     REAL,
                    live_price_ttc      REAL,
                    live_date           TEXT,
                    first_seen          TEXT NOT NULL,
                    last_seen           TEXT NOT NULL,
                    is_active           INTEGER NOT NULL DEFAULT 1
                )
            """)
            conn.execute("CREATE INDEX IF NOT EXISTS idx_products_site_active ON products(site_key, is_active)")
            conn.execute("CREATE INDEX IF NOT EXISTS idx_products_ean ON products(ean)")
            conn.execute("CREATE INDEX IF NOT EXISTS idx_products_mpn ON products(mpn)")


    # ──────────────────────
    #   LOADER(S)/SAVER(S)
    # ──────────────────────

    def _get_processed_urls_from_db(self) -> set:
        """
        Loads already processed URLs from the SQLite products table
        to avoid duplicate processing (cache checker).
        """
        db_path = os.path.join(self.DATABASE_PATH, f"{self.WEBSITE}_database.db")
        
        if not os.path.exists(db_path):
            return set()

        try:
            with sqlite3.connect(db_path) as conn:
                rows = conn.execute("SELECT url FROM products").fetchall()
                urls = {r[0] for r in rows}

                LOG.info(f"Products database cache: {len(urls)} URLs already processed.")
                return urls

        except Exception as e:
            LOG.exception(f"Error loading existing Products DB: {e}. Full restart needed.")
            return set()


    def _save_batch(self, batch_data: List[dict], is_emergency: bool = False) -> None:
        """Saves the current batch of data by upserting it into the SQLite database."""
        if not batch_data:
            return

        now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        db_path = os.path.join(self.DATABASE_PATH, f"{self.WEBSITE}_database.db")

        try:
            with sqlite3.connect(db_path) as conn:
                for data in batch_data:
                    
                    ean = data.get('EAN') if data.get('EAN') != "-" else None
                    mpn = data.get('MPN') if data.get('MPN') != "-" else None
                    brand = data.get('Brand') if data.get('Brand') != "-" else None
                    article = data.get('Article') if data.get('Article') != "-" else None
                    
                    # Validation des deux prix
                    raw_htva = data.get('Base Price (HTVA)')
                    raw_ttc = data.get('Base Price (TTC)')
                    
                    cat_price_htva = float(raw_htva) if isinstance(raw_htva, (int, float)) and raw_htva > 0 else None
                    cat_price_ttc = float(raw_ttc) if isinstance(raw_ttc, (int, float)) and raw_ttc > 0 else None

                    conn.execute("""
                        INSERT INTO products (
                            site_key, url, ean, mpn, brand, article, 
                            catalog_price_htva, catalog_price_ttc, catalog_date, first_seen, last_seen, is_active
                        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 1)
                        ON CONFLICT(url) DO UPDATE SET
                            ean = excluded.ean,
                            mpn = excluded.mpn,
                            brand = excluded.brand,
                            article = excluded.article,
                            catalog_price_htva = excluded.catalog_price_htva,
                            catalog_price_ttc = excluded.catalog_price_ttc,
                            catalog_date = excluded.catalog_date,
                            last_seen = excluded.last_seen,
                            is_active = 1
                    """, (
                        self.WEBSITE, data['ArticleURL'], ean, mpn, brand, article,
                        cat_price_htva, cat_price_ttc, data['Checked on'], now, now
                    ))
            
            if not is_emergency:
                LOG.info(f"Batch of {len(batch_data)} item(s) saved to {self.WEBSITE}_database.db.")

        except Exception as e:
            LOG.exception(f"CRITICAL: Failed to merge batch to SQLite due to {e}.")


    # ───────────────
    #   UTILITY/IES
    # ───────────────

    def _extract_field(self, soup: BeautifulSoup, field: str, jsonld: dict) -> str:
        """Extracts a product field from the HTML soup or JSON-LD."""
        sel = self.SELECTORS.get(field)
        result = None

        # --- JSON-LD ---
        if self.WEBSITEcfg.get("jsonld") is True:
            ld_map = {
                "ean": ["gtin13", "gtin", "gtin12", "gtin8", "isbn"],
                "mpn": ["mpn", "model"],
                "brand": ["brand"],
                "article": ["name"],
                "price": ["price"]
            }

            if field == "price":
                offers = jsonld.get("offers", {})
                if isinstance(offers, list) and offers:
                    result = offers[0].get("price")
                elif isinstance(offers, dict):
                    result = offers.get("price")
            else:
                for k in ld_map.get(field, []):
                    val = jsonld.get(k)
                    if val:
                        result = val.get("name") if isinstance(val, dict) else val
                        break

            if result:
                result_str = str(result).strip()
                PLACEHOLDERS = {"-", "", "NAN", "NONE", "NULL"}

                if field == "mpn":
                    ean_result = None
                    for k in ["gtin13", "gtin", "gtin12", "gtin8", "isbn", "sku"]:
                        val = jsonld.get(k)
                        if val:
                            ean_result = str(val).strip()
                            break
                    if ean_result and result_str == ean_result:
                        pass
                    elif result_str not in PLACEHOLDERS:
                        return result_str
                elif result_str not in PLACEHOLDERS:
                    return result_str

        # --- HTML FALLBACK ---
        if isinstance(sel, dict):
            tag        = sel.get("tag")
            cls        = sel.get("class")
            id_        = sel.get("id")
            text_cont  = sel.get("text_contains")
            replace_   = sel.get("replace")
            use_attr   = sel.get("use_attr")
            attr_dict  = sel.get("attr")
            type_      = sel.get("type")
            target_    = sel.get("target")
            split_on   = sel.get("split")
            label_     = sel.get("label")

            if type_ == "sibling" and text_cont:
                keywords = [text_cont] if isinstance(text_cont, str) else text_cont
                find_kwargs = {}
                if cls: find_kwargs['class_'] = cls
                for el in soup.find_all(tag, **find_kwargs):
                    if any(kw.lower() in el.get_text().lower() for kw in keywords):
                        sibling = el.find_next_sibling(target_.split('.')[-1] if target_ else "dd")
                        if sibling:
                            result = sibling.get_text(strip=True)
                            break

            elif label_:
                for row in soup.find_all(tag, class_=cls):
                    label_el = row.find(True, string=lambda s: s and label_.lower() in s.lower())
                    if label_el:
                        val_el = row.find_next(class_="attribute-table__column__value") or row.find_next("td")
                        if val_el:
                            result = val_el.get_text(strip=True)
                            break

            elif text_cont and not type_:
                keywords = [text_cont] if isinstance(text_cont, str) else text_cont
                find_kwargs = {k: v for k, v in [('class_', cls), ('id', id_)] if v}
                for el in soup.find_all(tag, **find_kwargs):
                    if any(kw.lower() in el.get_text().lower() for kw in keywords):
                        if target_ and '.' in target_:
                            t_tag, t_cls = target_.split('.', 1)
                            sub = el.find(t_tag, class_=t_cls)
                            result = sub.get_text(strip=True) if sub else None
                        else:
                            result = el.get_text(strip=True)
                        if result: break

            elif attr_dict or tag:
                find_kwargs = {k: v for k, v in [('class_', cls), ('id', id_)] if v}
                if split_on:
                    candidates = soup.find_all(tag, attr_dict) if attr_dict else soup.find_all(tag, **find_kwargs)
                    el = None
                    for candidate in candidates:
                        if split_on.upper() in candidate.get_text().upper():
                            el = candidate
                            break
                else:
                    el = soup.find(tag, attr_dict) if attr_dict else soup.find(tag, **find_kwargs)
                
                if el:
                    child_tag = sel.get("child_tag")
                    if child_tag:
                        child = el.find(child_tag)
                        result = child.get_text(strip=True) if child else el.get_text(strip=True)
                    else:
                        result = el.get(use_attr) if use_attr else el.get_text(strip=True)

            if result and split_on:
                parts = result.upper().split(split_on.upper())
                if len(parts) > 1:
                    raw = parts[-1].strip().split()[0] if parts[-1].strip() else "-"
                    result = raw.split("|")[0].strip() or "-"
                else:
                    result = "-"

            if result and replace_:
                result = result.upper().replace(replace_.upper(), "").strip()

        return str(result).strip() if result and str(result).lower() != "none" else "-"


    def _clean_ean(self, raw: str) -> str:
        """Standardizes the EAN by removing non-alphanumeric characters."""
        cleaned = "".join(filter(str.isalnum, str(raw))).upper()
        return cleaned if cleaned else "-"


    def _clean_mpn(self, raw: str) -> str:
        """Cleans the MPN by removing known brand names and extra whitespace."""
        brands = sorted(self.BRANDS, key=len, reverse=True)
        cleaned = str(raw).lower()

        for b in brands:
            cleaned = cleaned.replace(b.lower(), "")

        return " ".join(cleaned.split()).strip().upper() or "-"
    
    def _clean_price(self, raw_price: str) -> float:
        """
        Extrait le nombre d'une chaîne de caractères contenant des devises ou des espaces insécables.
        Convertit les virgules en points pour le typage FLOAT.
        """
        if not raw_price or raw_price == "-": 
            return 0.0
            
        # Remplacement de la virgule par un point
        cleaned = str(raw_price).replace(',', '.')
        
        # Le regex \d+(?:\.\d+)? cherche uniquement la première suite de chiffres (avec ou sans décimales)
        match = re.search(r'\d+(?:\.\d+)?', cleaned)
        
        if match:
            return float(match.group())
        return 0.0


    # ─────────────
    #   EXTRACTOR
    # ─────────────

    def _ONLINEextract_FINALproduct(self, link: str) -> Optional[dict]:
        """Scrapes a product page and returns a normalized dictionary."""
        
        ATTEMPT = 0

        PRODUCTvar = {
            'EAN': "-",
            'MPN': "-",
            'Brand': "-",
            'Article': "-",
            'Base Price (HTVA)': 0.0,
            'ArticleURL': link,
            'Checked on': datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        }

        while ATTEMPT < self.MAX_RETRIES:
            try:
                response = self.requests.get(link, headers=self.REQUESTS_HEADERS)
                response.raise_for_status()

                time.sleep(self.RETRY_DELAY) # Loading time (JS)
                soup = BeautifulSoup(response.content, "html.parser")

                JSONdata = {}
                for s in soup.find_all('script', type='application/ld+json'):
                    try:
                        parsed = json.loads(s.string)
                        items = [parsed] if isinstance(parsed, dict) else (parsed if isinstance(parsed, list) else [])
                        for item in items:
                            if isinstance(item, dict) and item.get("@type") == "Product":
                                JSONdata = item
                                break
                        if JSONdata:
                            break
                    except (json.JSONDecodeError, Exception):
                        continue

                # Extraction
                PRODUCTvar["EAN"] = self._clean_ean(self._extract_field(soup, "ean", JSONdata))
                PRODUCTvar["MPN"] = self._clean_mpn(self._extract_field(soup, "mpn", JSONdata))
                PRODUCTvar["Brand"] = self._extract_field(soup, "brand", JSONdata).upper()
                
                ARTICLE = self._extract_field(soup, "article", JSONdata)
                PRODUCTvar["Article"] = " ".join(ARTICLE.split()).replace('"', '""').strip('"')

                if PRODUCTvar["Brand"] == "-" and PRODUCTvar["Article"] != "-":
                    
                    # Normalisation de l'article : on retire les accents et on passe en majuscules
                    # ex: "DÉWALT Perceuse" -> "DEWALT PERCEUSE"
                    article_norm = unicodedata.normalize('NFKD', PRODUCTvar["Article"])\
                                              .encode('ASCII', 'ignore')\
                                              .decode('utf-8')\
                                              .upper()
                    
                    brands_sorted = sorted(self.BRANDS, key=len, reverse=True)
                    
                    for b in brands_sorted:
                        # Normalisation de la marque (au cas où il y a des accents dans brands.json)
                        brand_norm = unicodedata.normalize('NFKD', b)\
                                                .encode('ASCII', 'ignore')\
                                                .decode('utf-8')\
                                                .upper()
                        
                        if re.search(rf'\b{re.escape(brand_norm)}\b', article_norm):
                            # On sauvegarde la marque originale issue de brands.json (b.upper())
                            PRODUCTvar["Brand"] = b.upper() 
                            break

                # --- Price Handling ---
                PRICE_STR = self._extract_field(soup, "price", JSONdata)
                PRICE_FLOAT = self._clean_price(PRICE_STR)
                    
                # Assignation des deux prix au format FLOAT
                if PRICE_FLOAT > 0:
                    PRODUCTvar["Base Price (TTC)"] = round(PRICE_FLOAT, 2)
                    PRODUCTvar["Base Price (HTVA)"] = round(PRICE_FLOAT / self.VAT_RATE, 2)
                else:
                    PRODUCTvar["Base Price (TTC)"] = 0.0
                    PRODUCTvar["Base Price (HTVA)"] = 0.0

                return PRODUCTvar

            except requests.exceptions.HTTPError as http_err:
                if response.status_code == 404:
                    LOG.warning(f"Invalid link (404 Not Found). Saving failure for future skip: {link}")
                    return PRODUCTvar

                LOG.exception(f"HTTP Error ({response.status_code}) for {link}: {http_err}")
                ATTEMPT+=1
                time.sleep(self.RETRY_DELAY)

            except Exception as e:
                LOG.exception(f"Error during data extraction for product {link}: {e}")
                ATTEMPT+=1
                time.sleep(self.RETRY_DELAY)

        LOG.warning(f"Abandoning after {self.MAX_RETRIES} attempts for product {link}")
        return None


    # ────────────
    #   EXECUTOR
    # ────────────

    def run(self) -> None:
        """Executes the complete scraping pipeline using DB URLs."""
        LOG.info(f"LOADERengine process started for {self.WEBSITE}")

        all_active_urls = self._get_active_urls_from_db()
        processed_urls = self._get_processed_urls_from_db()

        self.URLs = [url for url in all_active_urls if url not in processed_urls]
        LOG.info(f"Found new link(s) to process: {len(self.URLs)} (out of {len(all_active_urls)} active) for {self.WEBSITE}")

        PRODUCTS_BATCH: List[dict] = []

        try:
            for PRODUCTurl in self.URLs:
                try:
                    data = self._ONLINEextract_FINALproduct(PRODUCTurl)

                    LOG.debug(data)

                    if data is None: 
                        continue

                    PRODUCTS_BATCH.append(data)
                    self.SAVE_COUNTER += 1

                    if self.SAVE_COUNTER >= self.SAVE_THRESHOLD:
                        self._save_batch(PRODUCTS_BATCH)
                        
                        self.SAVE_COUNTER = 0
                        PRODUCTS_BATCH = []

                    time.sleep(random.uniform(0.5, 1.5)) # Politeness delay

                except Exception as e:
                    LOG.exception(f"An unexpected error occurred for URL {PRODUCTurl}: {e}")
                    continue

            # Sauvegarde finale des résidus du batch
            if PRODUCTS_BATCH: 
                self._save_batch(PRODUCTS_BATCH)

        except Exception as e:
            if PRODUCTS_BATCH: 
                self._save_batch(PRODUCTS_BATCH, is_emergency=True)
            LOG.warning(f"Emergency save triggered due to critical error: {e}")

        LOG.info(f"{self.WEBSITE} loader terminated...")